### ISSUE TITLE
Finite Difference Operator

### ISSUE THREAD

**Issue by rubabanoyireeta** [heiwot26/Dishwashers#3]
In the code, we're given the finite difference operator for (d squared/dx squared) operator. Can someone look up the finite difference operator for d/dt please?

<img width="1397" alt="Screenshot 2022-11-09 at 18 00 56" src="https://user-images.githubusercontent.com/116881776/200905690-a9bf5fd6-251d-40b7-90ec-ebc02857da58.png">

**Comment by ZJAP024** [comment]
Hi so we won't need the finite difference operator for d/dt. We have the second order central finite difference operator for d^2/dx^2, which in the code will be done by the imported module FinDiff, which takes as input an array of values and outputs the derivative of that array along an axis, with an input desired accuracy order. This will be all we need to find the Hamiltonian, which in order to calculate U using the Crank Nicholson algorithm will be all we need.

**Comment by ZJAP024** [comment]
Closing issue
